#!/bin/ksh
#  UNIX Shell script to generate the monthly usage reports for all RETS SVCs.
#  These reports are used by Tom O'Brien for his monthly chargeback activity.
#  PLEASE NOTE: it is intended that this report should only be run once a month
#  only ON THE FIRST of THE MONTH. (mostly because it is more difficult to
#  calculate the END of a month)
#  The input file(s) are previously generated by running the program "svc_volume_data.ksh".
#  It is ASSUMED that these input files were generated on the SAME DATE as this script is run.
#  The SVCs included in these reports are:
#  svcmbgt01v (OPTIONAL: in test lab), svcmbge01v , svcmbgc01v ,svclebe01v ,
#  svclebc01v , svcspre01v , svcsprc01v .
#  Kirk Naeve, March 2013.
#
cd /opt/SSE
#
for SVC in svcmbgt01v svcmbgp01v svcmbge01v svcmbgc01v svclebp01v svclebe01v svclebc01v svcsprp01v svcspre01v svcsprc01v
do
        FILE="/users/svcadmin/reports/svc/volumes/"${SVC}"_Volumes_"$(date '+%Y%m%d')".txt"
	cp ${FILE} .
        FILE=""${SVC}"_Volumes_"$(date '+%Y%m%d')".txt"
        /opt/SSE/jscode.pl ${FILE}
	rm ${FILE}
done
#
# Run the UX (Oxford) SVC reports.
#
for SVC_name in SVCOXFE01V SVCOXFC01V
do
        FILE="/users/svcadmin/reports/svc/volumes/"${SVC_name}"_Volumes_"$(date '+%Y%m%d')".txt"
        cp ${FILE} .
        FILE=""${SVC_name}"_Volumes_"$(date '+%Y%m%d')".txt"
        /opt/SSE/jscode.pl ${FILE}
        rm ${FILE}
done
#
# Send mail to let someone know that the reports have been run.
LIST=/var/tmp/reports.txt
echo "The MONTHLY SVC Capacity Report has been run." > ${LIST}
echo "" >> ${LIST}
ls -l /opt/SSE/svc*.txt >> ${LIST}
mailx -s "Monthly SVC storage reports have been run"  kirk.naeve@reedelsevier.com < ${LIST}
#
rm ${LIST}
